### ISSUE TITLE
Since messaging went away a long time ago

### ISSUE THREAD

**Issue by crichmond** [MrChrisWeinert/MAMEIron#6]
I've been pondering working on a .NET based front end for MAME for a long time. Then I came across your project.  Do you have any further plans or are you going to still work on it or want some help?  
Cheers

**Comment by MrChrisWeinert** [comment]
Funny timing, I was actually planning to pick this project back up since I'm building a new cabinet! MAMEIron, in its current form needs some love. At least 1680x1050 --> 1920x1080 :)

Bigger picture, I'd love to move off of .NET Framework and over to .NET 8 so we wouldn't be tied to Windows. I also kicked around the idea of using .NET MAUI for the ui, but I haven't played with it yet. If the current UI could be reproduced (or made better/prettier/more performant) on cross-platform .net, that'd be a huge accomplishment. I'd love some help with any/all of this if you're interested!!

**Comment by crichmond** [comment]
That's pretty funny. I was thinking exactly that.  "It would be cool if he
was going to move to another more modern cross platform UI and update the
code ".
Yeah..I'd definitely want to work on this and I have a *bit* of MAUI
experience.

Would you want to maybe get on Discord or Teams or something and discuss
the plan and steps at some point?

Thanks,
Chris

**Comment by MrChrisWeinert** [comment]
Yea, definitely!
Can you hit me up on Twitter and shoot me a DM (MrChrisWeinert) to work out the logistics. Teams/Discord both work.

**Comment by crichmond** [comment]
Sorry for the late reply.  For some reason this conversation got pushed
back into a sub folder and I didn't see it until I realized it had been a
bit searched for it.

I'll hit you up...looking forward to it.

**Comment by MrChrisWeinert** [comment]
No problem! I'm a Discord noob, so let me know if you get my request (zyx..)
